version: '3.4'

services:
  ui: 
    image: karolniedziela/fitweb-front
    build: 
      context: ../Frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports: 
      - 8888:80
    depends_on: 
      - backend.api
      - db
  backend.api:
    image: ${DOCKER_REGISTRY-}backendapi
    build:
      context: .
      dockerfile: src/Backend.Api/Dockerfile
    environment:
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=Your_password123"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "8000:80"
    depends_on:
      - db
    restart: on-failure
  
  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: db
    ports: 
      - "1433:1433"
    environment:
      - SA_PASSWORD=Xkp7VmE6YHVDM
      - ACCEPT_EULA=Y